# Generated by Django 5.2.5 on 2025-11-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_adminregistration_remove_paymenttransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistration',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
