# Generated by Django 5.2.5 on 2025-11-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_adminregistration_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
